---
- name: Download cert-manager
  ansible.builtin.get_url:
    url: {{ cert_manager_manifest_url }}
    dest: {{ downlad_directory }}
    mode: '0644'
    backup: true
  tags:
    - rke2
    - rke2_cert-manager
    - rke2_cert-manager_download

- name: Apply cert-manager to k8s
  kubernetes.core.k8s:
    state: present
    src: {{ cert_manager_manifest_file }}
  tags:
    - rke2
    - rke2_cert-manager
    - rke2_cert-manager_install

- include_tasks: wait2complete.yml
  vars:
    namespace: cert-manager
  tags:
    - rke2
    - rke2_cert-manager
    - rke2_cert-manager_wait
  when: not ansible_check_mode
