---
- name: Download local-path-provisioner
  ansible.builtin.get_url:
    url: {{ local_path_provisioner_manifest_url }}
    dest: {{ downlad_directory }}
    mode: '0644'
    backup: true
  tags:
    - rke2
    - rke2_local-path-provisioner
    - rke2_local-path-provisioner_download

- name: Apply local-path-provisioner to k8s
  kubernetes.core.k8s:
    state: present
    src: {{ local_path_provisioner_manifest_file }}
  tags:
    - rke2
    - rke2_local-path-provisioner
    - rke2_local-path-provisioner_install

- include_tasks: wait2complete.yml
  vars:
    namespace: local-path-storage
  tags:
    - rke2
    - rke2_local-path-provisioner
    - rke2_local-path-provisioner-wait
  when: not ansible_check_mode

- name: Set local-path-provisioner as default
  kubernetes.core.k8s:
    state: patched
    api_version: storage.k8s.io/v1
    kind: StorageClass
    name: local-path
    definition:
      metadata:
        annotations:
          storageclass.kubernetes.io/is-default-class: "true"
  tags:
    - rke2
    - rke2_local-path-provisioner
    - rke2_local-path-provisioner_patch
