---
- name: Check system resources
  ansible.builtin.assert:
    that:
      - ansible_processor_vcpus >= 2
        # There is some, not exact, reserved memory
        # which is not accessible to userspace. Setting
        # 4096 won't pass this assertion.
      - ansible_memtotal_mb >= 3900
    msg: RKE2 (kubernetes) needs at last two CPU and 4GB RAM
  tags:
    - rke2
    - rke2_resources_assertion

# https://docs.rke2.io/advanced
- name: Create "{{ etc_default_dir }}"/rke2-agent
  template:
    src: "rke2-server-agent.j2"
    dest: "{{ etc_default_dir }}/rke2-agent"
    owner: root
    group: root
    mode: '0644'
  when:
    proxy is defined
  tags:
    - rke2
    - rke2_http_proxy

# https://docs.rke2.io/advanced
- name: Create "{{ etc_default_dir }}"/rke2-server
  template:
    src: "rke2-server-agent.j2"
    dest: "{{ etc_default_dir }}/rke2-server"
    owner: root
    group: root
    mode: '0644'
  tags:
    - rke2
    - rke2_http_proxy
  when:
    proxy is defined and ansible_facts['rke2_cluster_role'] == "server"

- name: Install rke2
  include_tasks: rke2.yml
  tags:
    - rke2
    - rke2_install

- name: install local-path-provisioner
  include_tasks: local-path-provisioner.yml
  tags:
      - rke2
      - rke2_local-path-provisioner

- name: Install cert-manager
  include_tasks: cert-manager.yml
  tags:
    - rke2
    - rke2_cert-manager